name: Enable auto-merge
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  enable-automerge:
    # Enable automerge to merge pull requests from Renovate automatically.
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: generate_token
        with:
          app-id: ${{secrets.gh_app_id}}
          private-key: ${{secrets.gh_app_private_key}}
          owner: ${{ github.repository_owner }}
          repositories: ${{github.event.repository.name}}
      - run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto --delete-branch "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # Use GitHub App to trigger GitHub Actions Workflow by merge commit.
          PR_NUMBER: ${{github.event.pull_request.number}}
