name: Hide comments
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false
env:
  GH_COMMENT_SHA1: ${{inputs.ref}}
jobs:
  hide-comment:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.ref}}
          persist-credentials: false
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: generate_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.gh_app_private_key }}
          owner: ${{ github.repository_owner }}
          repositories: ${{github.event.repository.name}}
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.41.0
        env:
          AQUA_GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
